### ISSUE TITLE
Parse data using JSON instead of XML.

### ISSUE THREAD

**Issue by kaushiksk** [kaushiksk/pymdb#2]
Currently the program grabs the xml data for a given movie.
But JSON is much more reader-friendly!
- Add code that requests for data from the API in json format using a custom url encoded string.
  Change the `r` parameter in the urlencode from xml to json
- Store the obtained json string in a jsonstuff instance variable
- Emulate the info function and write a jsoninfo function that parses data after reading the json string.

Resources:
Read up on `JSON`,`urllib` `omdbapi.com`

**Comment by palnabarun** [comment]
Working on it
